GET http://localhost:3002/api/categories

GET http://localhost:3002/api/categories/56528e6e-af49-413d-a6ff-fbf95e0cea40

POST http://localhost:3002/api/categories/
Content-Type: application/json

{
    "name": "Hola",
    "email": "pxndxs@pxndxs.com",
    "message": "Hola que hace"
}
