GET http://localhost:3002/api/department-categories

GET http://localhost:3002/api/department-categories/56528e6e-af49-413d-a6ff-fbf95e0cea40

POST http://localhost:3002/api/department-categories/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMyM2Q0YjYyLTRiZTAtNGMyMS1hNzA0LTRiMjA3MmQyZjM1MiIsImlhdCI6MTY5OTMxOTI4NiwiZXhwIjoxNjk5NDA1Njg2fQ.slG7UMTGbt126DELOVbFr0n00A-Jr3fVvsb6u0wwmyY
Content-Type: application/json

{
    "name": "Customer 2"
}

PATCH http://localhost:3002/api/department-categories/e159c93a-dd2b-41ba-8a44-36ccfbf1353f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMyM2Q0YjYyLTRiZTAtNGMyMS1hNzA0LTRiMjA3MmQyZjM1MiIsImlhdCI6MTY5OTMxOTI4NiwiZXhwIjoxNjk5NDA1Njg2fQ.slG7UMTGbt126DELOVbFr0n00A-Jr3fVvsb6u0wwmyY
Content-Type: application/json

{
    "name": "Department 2",
    "isActive": true
}

DELETE http://localhost:3002/api/department-categories/56528e6e-af49-413d-a6ff-fbf95e0cea40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ4ZmQyYzZhLWI1OGItNDdhYi04OTVlLWVlNTdiYTRjZTk5YiIsImlhdCI6MTY5OTMyODQxNCwiZXhwIjoxNjk5NDE0ODE0fQ.CuBAI2fsw699UDg2QuEvEanLixkHGeKIofA2qIYo_5k
