
GET http://localhost:3002/api/users

GET http://localhost:3002/api/users/48fd2c6a-b58b-47ab-895e-ee57ba4ce99b

POST http://localhost:3002/api/users
Content-Type: application/json

{
  "name": "Pxndxs xD",
  "email": "pxndxs@pxndxs.com",
  "username": "pxndxs",
  "password": "Hola1234",
  "role": "admin"
}

PATCH http://localhost:3002/api/users/48fd2c6a-b58b-47ab-895e-ee57ba4ce99b
Content-Type: application/json

{
  "name": "Pxnditx",
  "isActive": true
}

DELETE http://localhost:3002/api/users/48fd2c6a-b58b-47ab-895e-ee57ba4ce99b
